### ISSUE TITLE
Don't add comment if already inside a comment

### ISSUE THREAD

**Issue by wesbos** [drKnoxy/eslint-disable-snippets#10]
Love this extension - right now if I'm already in a comment - it would be nice to not add the `//` 

like this

Start: `/* eslint */` 

Then the snippet gives me this:

<img width="423" alt="Screenshot 2023-01-10 at 10 43 10 AM" src="https://user-images.githubusercontent.com/176013/211596355-204ec7b8-f39f-42fa-ba26-80bbc9c94890.png">

**Comment by drKnoxy** [comment]
I googled around and don't see any support for knowing if you are in a comment block already.
Going to close out as will not address.

Have a good one Wes, I've enjoyed your content over the years.
